// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI commands (migrate, db push, studio, etc.) need the direct,
    // non-pooled connection — Supabase's pgbouncer pooler doesn't support
    // the advisory locks migrations rely on, which causes the CLI to hang.
    url: process.env["DIRECT_URL"],
  },
});
