import { HOURS_PER_DAY, monthlyFromHourly } from "@/lib/employee"
import { holidayOn } from "@/lib/holidays"

// ---------------------------------------------------------------------------
// Payroll
//
// Pure arithmetic, no database and no React, so the rules that decide what
// someone is paid can be read — and corrected — in one place. Every figure on
// the payroll page comes from here.
//
// The rules, as the office states them:
//
//   Basic       whole hours only, capped at 8 a day. A normal day is nine
//               hours on site: eight worked and one unpaid break. Minutes
//               don't count — 7h59m is seven hours.
//   Overtime    approved hours only, at the plain hourly rate. Staying late
//               without an approved request pays nothing.
//   Night       an extra 10% of the hourly rate for time worked 22:00–06:00.
//   Holiday     worked on a regular holiday, the day pays double, and working
//               it is what earns it. Not worked, it pays a normal day — but
//               only to someone who was present on the workday before it.
//               Absent before it and absent on it, the day pays nothing.
//   Deductions  SSS, PhilHealth and Pag-IBIG are monthly, and payroll runs
//               twice a month, so half comes off each cutoff.
//
// One of those is a deliberate house rule rather than the statutory minimum,
// and it is one constant if that ever changes: overtime is paid flat where the
// Labor Code sets 125% for an ordinary day.
// ---------------------------------------------------------------------------

/** Paid hours in a normal day. The ninth hour on site is the meal break. */
export const REGULAR_HOURS_PER_DAY = HOURS_PER_DAY

/** Unpaid, and the reason a full day on site is nine hours rather than eight. */
export const UNPAID_BREAK_HOURS = 1

/**
 * A day has to run past this before a single overtime hour is earned.
 *
 * Eight paid hours plus the unpaid break: nine hours on site is an ordinary
 * day, not a long one. Someone approved for two hours has to be on the clock
 * for eleven before both are worked.
 */
export const OVERTIME_STARTS_AFTER_HOURS =
  REGULAR_HOURS_PER_DAY + UNPAID_BREAK_HOURS

/**
 * Approved overtime is paid at the employee's plain hourly rate, by decision.
 * The Labor Code's ordinary-day minimum is 1.25 — change this one number to
 * adopt it, and every figure on the page follows.
 */
export const OVERTIME_MULTIPLIER = 1

/** A regular holiday worked pays twice the day's rate. */
export const HOLIDAY_MULTIPLIER = 2

/**
 * How far back to look for the workday before a regular holiday.
 *
 * An unworked holiday is only paid to someone who was present on the workday
 * *before* it — but this system has no roster, so it cannot say which days a
 * person was meant to be at work. Testing only the previous calendar day would
 * deny the pay to nearly everybody: National Heroes Day is always a Monday, and
 * nobody punches on a Sunday.
 *
 * So the preceding workday is taken to be the most recent day the employee was
 * actually present, and this is how far back that search goes. Five days covers
 * a weekend either side of the holiday; past that, someone who has not been
 * seen for a working week is absent, and an absence before a holiday is exactly
 * what the rule withholds the pay for.
 */
export const HOLIDAY_QUALIFYING_LOOKBACK_DAYS = 5

/** The night differential is a premium on top of the hour, not a rate for it. */
export const NIGHT_DIFFERENTIAL_RATE = 0.1
export const NIGHT_STARTS_HOUR = 22
export const NIGHT_ENDS_HOUR = 6

export const PAGIBIG_MONTHLY = 200
/** Employee share. The 5% total is split evenly with the employer. */
export const PHILHEALTH_EMPLOYEE_RATE = 0.025

/** Pay runs on the 1st–15th and the 16th–end, so monthly amounts halve. */
export const CUTOFFS_PER_MONTH = 2

/** Money, to the centavo. Kept off the display layer so totals always agree. */
function money(value: number) {
  return Math.round(value * 100) / 100
}

// ---------------------------------------------------------------------------
// SSS
// ---------------------------------------------------------------------------
//
// Circular 2024-006, effective January 2025. The published table is 46 rows of
// brackets, but it is generated by a rule and the rule is far easier to keep
// right than a transcription: the Monthly Salary Credit is the compensation
// rounded to the nearest ₱500 within a floor of ₱5,000 and a ceiling of
// ₱35,000, and the employee pays 5% of it.
//
// That 5% covers both columns the table prints separately — regular SS on the
// first ₱20,000 of MSC and the Mandatory Provident Fund on the rest. An MSC of
// ₱20,500 is ₱1,000 + ₱25 in the table and ₱1,025 here; ₱35,000 is ₱1,000 +
// ₱750 there and ₱1,750 here. The split matters to SSS, not to take-home, so
// the parts are reported separately below for the payslip while the deduction
// itself is the one figure.

export const SSS_MIN_MSC = 5000
export const SSS_MAX_MSC = 35000
export const SSS_MSC_STEP = 500
/** Above this, the excess goes to the provident fund rather than regular SS. */
export const SSS_REGULAR_MSC_CEILING = 20000
export const SSS_EMPLOYEE_RATE = 0.05

/** Which bracket of the schedule a monthly compensation falls in. */
export function sssMonthlySalaryCredit(monthlyPay: number) {
  const stepped =
    Math.round(monthlyPay / SSS_MSC_STEP) * SSS_MSC_STEP
  return Math.min(Math.max(stepped, SSS_MIN_MSC), SSS_MAX_MSC)
}

export type SssShare = {
  monthlySalaryCredit: number
  /** Regular Social Security programme. */
  regular: number
  /** Mandatory Provident Fund, on any MSC above ₱20,000. */
  provident: number
  total: number
}

export function sssEmployeeShare(monthlyPay: number): SssShare {
  const msc = sssMonthlySalaryCredit(monthlyPay)
  const regular = money(
    Math.min(msc, SSS_REGULAR_MSC_CEILING) * SSS_EMPLOYEE_RATE
  )
  const provident = money(
    Math.max(0, msc - SSS_REGULAR_MSC_CEILING) * SSS_EMPLOYEE_RATE
  )

  return {
    monthlySalaryCredit: msc,
    regular,
    provident,
    total: money(regular + provident),
  }
}

// ---------------------------------------------------------------------------
// Hours
// ---------------------------------------------------------------------------

/** Minutes to paid hours: whole hours only, never rounded up. */
export function wholeHours(minutes: number) {
  return Math.max(0, Math.floor(minutes / 60))
}

function overlapMinutes(
  fromA: Date,
  toA: Date,
  fromB: Date,
  toB: Date
) {
  const start = Math.max(+fromA, +fromB)
  const end = Math.min(+toA, +toB)
  return end > start ? (end - start) / 60_000 : 0
}

/**
 * Minutes of a shift that fall inside the 22:00–06:00 window.
 *
 * Walked night by night rather than reasoned about, because a shift can start
 * before the window, end after it, or sit entirely inside one — and a punch is
 * allowed to run past midnight. The loop covers the day before the punch
 * through the day after it, which is every window a single shift can touch.
 */
export function nightMinutes(timeIn: Date, timeOut: Date) {
  let total = 0

  const cursor = new Date(timeIn)
  cursor.setHours(0, 0, 0, 0)
  cursor.setDate(cursor.getDate() - 1)

  const last = new Date(timeOut)
  last.setHours(0, 0, 0, 0)
  last.setDate(last.getDate() + 1)

  while (cursor <= last) {
    const nightStart = new Date(cursor)
    nightStart.setHours(NIGHT_STARTS_HOUR, 0, 0, 0)

    const nightEnd = new Date(cursor)
    nightEnd.setDate(nightEnd.getDate() + 1)
    nightEnd.setHours(NIGHT_ENDS_HOUR, 0, 0, 0)

    total += overlapMinutes(timeIn, timeOut, nightStart, nightEnd)
    cursor.setDate(cursor.getDate() + 1)
  }

  return total
}

// ---------------------------------------------------------------------------
// A day
// ---------------------------------------------------------------------------

export type PayrollDayInput = {
  /** Local midnight of the day worked. */
  date: Date
  timeIn: Date
  /** Null while the punch is still open — an unclosed day pays nothing. */
  timeOut: Date | null
  /** Hours the office actually granted. Requested-but-unapproved is zero. */
  approvedOvertimeHours: number
}

export type PayrollDay = {
  date: string
  /** What the clock says, to the minute, before any rule is applied. */
  renderedMinutes: number
  regularHours: number
  /** Overtime actually paid: approved, and stayed for. */
  overtimeHours: number
  /** What the office granted. Never less than `overtimeHours`. */
  approvedOvertimeHours: number
  nightHours: number
  /** Night hours that fall inside paid time, and so are paid at rate + 10%. */
  nightPaidHours: number
  holiday: string | null
  worked: boolean
  /** Regular hours at the plain rate, *excluding* the night hours below. */
  basicPay: number
  overtimePay: number
  nightPay: number
  /** Basic pay's holiday half — the second 100%, shown separately. */
  holidayPremium: number
  total: number
}

export function computeDay(
  input: PayrollDayInput,
  hourlyRate: number
): PayrollDay {
  const holiday = holidayOn(input.date)
  const date = input.date.toISOString()

  // An open punch has no length, and guessing one would invent hours nobody
  // worked. It shows as a day with no pay until the office closes it.
  if (!input.timeOut) {
    return {
      date,
      renderedMinutes: 0,
      regularHours: 0,
      overtimeHours: 0,
      approvedOvertimeHours: Math.max(0, input.approvedOvertimeHours),
      nightHours: 0,
      nightPaidHours: 0,
      holiday,
      worked: true,
      basicPay: 0,
      overtimePay: 0,
      nightPay: 0,
      holidayPremium: 0,
      total: 0,
    }
  }

  const renderedMinutes = Math.max(
    0,
    (+input.timeOut - +input.timeIn) / 60_000
  )

  const renderedHours = wholeHours(renderedMinutes)

  // Capped at eight: the ninth hour on site is the unpaid break, and anything
  // past that is overtime or it is nothing.
  const regularHours = Math.min(renderedHours, REGULAR_HOURS_PER_DAY)

  // An approval is permission to work the hours, not payment for them. What
  // gets paid is whichever is smaller: what the office granted, or what the
  // clock shows past the ninth hour. Two hours approved and a 10h30m day is
  // one hour of overtime — the second was never worked, and whole hours only,
  // so the thirty minutes are not half of one.
  const approvedOvertimeHours = Math.max(0, input.approvedOvertimeHours)
  const overtimeWorked = Math.max(
    0,
    renderedHours - OVERTIME_STARTS_AFTER_HOURS
  )
  const overtimeHours = Math.min(approvedOvertimeHours, overtimeWorked)
  const nightHours = wholeHours(nightMinutes(input.timeIn, input.timeOut))

  // Every regular hour at the plain rate, night or not. This is the figure the
  // rest of the day is built from, and it does not move.
  const regularPay = regularHours * hourlyRate

  // The night hours that fall inside paid regular time. A long punch can render
  // more night minutes than it is paid for — past the eight-hour cap the hours
  // are overtime or they are nothing — and an hour nobody is paid for cannot be
  // paid at a night rate.
  const nightPaidHours = Math.min(nightHours, regularHours)

  // A night hour is worth the hourly rate *plus* ten per cent, and this is the
  // line that says so. The hour's own pay is carried here rather than on the
  // basic line, because "night differential 8.75" against a rate of 87.50 reads
  // as though the hour was worth a tenth of a day hour — the opposite of what
  // it means. Every paid hour still appears exactly once, and the day's total
  // is unchanged by where it is shown.
  //
  // Night hours outside paid time keep the premium alone: there is no base pay
  // under them to add ten per cent to.
  const nightPay =
    nightPaidHours * hourlyRate * (1 + NIGHT_DIFFERENTIAL_RATE) +
    (nightHours - nightPaidHours) * hourlyRate * NIGHT_DIFFERENTIAL_RATE

  const basic = regularPay - nightPaidHours * hourlyRate

  // Doubled against the whole day's regular pay, not against what is left on
  // the basic line — a night shift on a holiday must not lose the holiday on
  // the hours that moved across.
  const holidayPremium = holiday ? regularPay * (HOLIDAY_MULTIPLIER - 1) : 0
  const overtimePay = overtimeHours * hourlyRate * OVERTIME_MULTIPLIER

  return {
    date,
    renderedMinutes,
    regularHours,
    overtimeHours,
    approvedOvertimeHours,
    nightHours,
    nightPaidHours,
    holiday,
    worked: true,
    basicPay: money(basic),
    overtimePay: money(overtimePay),
    nightPay: money(nightPay),
    holidayPremium: money(holidayPremium),
    total: money(basic + holidayPremium + overtimePay + nightPay),
  }
}

// ---------------------------------------------------------------------------
// A cutoff
// ---------------------------------------------------------------------------

/**
 * The regular holidays inside a cutoff, walked a day at a time — sixteen
 * iterations at the outside, against a lookup that is already indexed by year.
 *
 * Here rather than beside the payroll action because a "use server" module may
 * only export async functions, and because the page needs it too.
 */
export function holidaysBetween(start: Date, end: Date) {
  const found: { date: Date; name: string }[] = []
  const cursor = new Date(start)

  while (cursor <= end) {
    const name = holidayOn(cursor)
    if (name) found.push({ date: new Date(cursor), name })
    cursor.setDate(cursor.getDate() + 1)
  }

  return found
}

export type UnworkedHoliday = {
  date: string
  name: string
  /** Zero when the day before was an absence — see `qualifiesOn`. */
  pay: number
  /**
   * Whether the employee was present on the workday before it.
   *
   * Carried rather than filtered away so the payslip can show the day and say
   * why it paid nothing. A holiday that silently vanishes from the breakdown
   * is a question the office has to ring somebody about.
   */
  qualified: boolean
}

/** "2026-08-31" from local parts — how a day is keyed for comparison here. */
function localDayKey(date: Date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, "0")
  const day = String(date.getDate()).padStart(2, "0")
  return `${year}-${month}-${day}`
}

/**
 * Was this employee present on the workday before the holiday?
 *
 * The rule the office states, in four cases:
 *
 *   before   holiday   paid
 *   ───────────────────────────────────────────────
 *   no       no        nothing at all
 *   yes      yes       double
 *   yes      no        a normal day
 *   no       yes       double — working it is what earns it
 *
 * Only the third case needs asking, and it is the one this answers: the other
 * three fall out of whether the holiday itself was worked. Walks back from the
 * holiday for the most recent day the employee was present, stopping at
 * `HOLIDAY_QUALIFYING_LOOKBACK_DAYS`.
 *
 * An earlier holiday the employee was *paid* for counts as being present — a
 * paid day is not an absence, which matters for Good Friday, whose preceding
 * day is Maundy Thursday.
 */
function qualifiesOn(
  holiday: Date,
  presentKeys: ReadonlySet<string>,
  paidHolidayKeys: ReadonlySet<string>
) {
  const cursor = new Date(holiday)

  for (let back = 0; back < HOLIDAY_QUALIFYING_LOOKBACK_DAYS; back++) {
    cursor.setDate(cursor.getDate() - 1)
    const key = localDayKey(cursor)
    if (presentKeys.has(key) || paidHolidayKeys.has(key)) return true
  }

  return false
}

/**
 * A one-off correction the office made to this cutoff.
 *
 * Signed: positive pays more, negative pays less. The computation only needs
 * the number and the words; who added it and when belong to the record, not to
 * the arithmetic.
 */
export type AdjustmentInput = { label: string; amount: number }

export type Payslip = {
  hourlyRate: number
  monthlyBasis: number
  days: PayrollDay[]
  /**
   * Regular holidays in the cutoff the employee did not work.
   *
   * Includes the ones that paid nothing because the day before was an absence
   * — each carries its own `qualified` flag, so the breakdown can show the day
   * and say why rather than leaving it out.
   */
  unworkedHolidays: UnworkedHoliday[]

  daysWorked: number
  regularHours: number
  /** Overtime paid: approved, and actually stayed for. */
  overtimeHours: number
  /**
   * Overtime the office approved across the cutoff. Larger than
   * `overtimeHours` when somebody was granted hours they didn't end up
   * working — worth showing, or the payslip looks like it lost some.
   */
  approvedOvertimeHours: number
  nightHours: number
  /** Of those, the ones paid at rate + 10% because they were inside paid time. */
  nightPaidHours: number

  /** Regular hours at the plain rate, *excluding* the night hours. */
  basicPay: number
  holidayPay: number
  overtimePay: number
  /** The night hours in full: their own pay plus the 10% premium. */
  nightPay: number
  /** Adjustments that pay more, already inside `gross`. */
  adjustmentAdditions: number
  gross: number

  sss: SssShare
  /**
   * Halved: these are monthly figures and this is one of two cutoffs.
   *
   * `sss`/`philhealth`/`pagibig` are what the schedules call for; `total` is
   * what could actually be taken out of this cutoff's pay, and `shortfall` is
   * the rest. A contribution is withheld *from* wages, so it can never exceed
   * them — without that, a fortnight nobody worked came out as a negative
   * payslip, which reads as the employee owing the company money.
   */
  deductions: {
    sss: number
    philhealth: number
    pagibig: number
    /** Adjustments that pay less, as a positive figure. */
    adjustments: number
    /** Everything the schedules ask for this cutoff. */
    due: number
    /** What the pay could cover. Never more than gross. */
    total: number
    /** Due but uncollectable this run — the office carries it. */
    shortfall: number
  }

  net: number
}

export function computePayslip({
  hourlyRate,
  days,
  daysBeforeCutoff = [],
  holidaysInCutoff,
  adjustments = [],
}: {
  hourlyRate: number
  days: PayrollDayInput[]
  /**
   * Attendance from the days just before the cutoff opened.
   *
   * Never paid and never counted — read only to answer "were they present
   * before this holiday" for a holiday sitting on the first days of the
   * period, whose qualifying day belongs to the cutoff before this one.
   */
  daysBeforeCutoff?: PayrollDayInput[]
  /** Every regular holiday falling inside the cutoff. */
  holidaysInCutoff: { date: Date; name: string }[]
  /** What the office added or took off by hand this cutoff. */
  adjustments?: AdjustmentInput[]
}): Payslip {
  const computed = days.map((day) => computeDay(day, hourlyRate))

  // Keyed off the input dates, not off `computed[].date` — that one is an ISO
  // string of local midnight, which in Manila reads as the *previous* day once
  // it has been through UTC. Every key here is local, so they compare.
  const workedKeys = new Set(days.map((day) => localDayKey(day.date)))

  // Presence, not paid hours: the test is whether somebody turned up, and a
  // punch is the evidence of that. A day still on the clock pays nothing but
  // is not an absence, so it qualifies the holiday after it.
  const presentKeys = new Set(
    [...days, ...daysBeforeCutoff].map((day) => localDayKey(day.date))
  )

  // Chronological, because a holiday can qualify the one after it: Good Friday
  // follows Maundy Thursday, and being paid for the Thursday is not an absence
  // on the Friday. Walking them in order means the earlier answer is known by
  // the time the later one is asked.
  const paidHolidayKeys = new Set<string>()
  const unworkedHolidays: UnworkedHoliday[] = []

  for (const holiday of [...holidaysInCutoff].sort((a, b) => +a.date - +b.date)) {
    const key = localDayKey(holiday.date)

    // Worked holidays are already paid — at double — by `computeDay`, and
    // working the day is itself what earns it, whatever came before.
    if (workedKeys.has(key)) {
      paidHolidayKeys.add(key)
      continue
    }

    const qualified = qualifiesOn(holiday.date, presentKeys, paidHolidayKeys)
    if (qualified) paidHolidayKeys.add(key)

    unworkedHolidays.push({
      date: holiday.date.toISOString(),
      name: holiday.name,
      pay: qualified ? money(REGULAR_HOURS_PER_DAY * hourlyRate) : 0,
      qualified,
    })
  }

  const sum = (pick: (day: PayrollDay) => number) =>
    computed.reduce((total, day) => total + pick(day), 0)

  const worked = computed.filter((day) => day.regularHours > 0).length

  const basicPay = money(sum((day) => day.basicPay))
  const holidayPay = money(
    sum((day) => day.holidayPremium) +
      unworkedHolidays.reduce((total, holiday) => total + holiday.pay, 0)
  )
  const overtimePay = money(sum((day) => day.overtimePay))
  const nightPay = money(sum((day) => day.nightPay))
  // The sign is the whole meaning: what pays more joins the earnings, what
  // pays less joins the deductions. Split here so the payslip can show each in
  // the half it belongs to rather than as one net number nobody can check.
  const adjustmentAdditions = money(
    adjustments
      .filter((entry) => entry.amount > 0)
      .reduce((total, entry) => total + entry.amount, 0)
  )
  const adjustmentDeductions = money(
    adjustments
      .filter((entry) => entry.amount < 0)
      .reduce((total, entry) => total - entry.amount, 0)
  )

  const gross = money(
    basicPay +
      holidayPay +
      overtimePay +
      nightPay +
      adjustmentAdditions
  )

  // Contributions follow the contractual monthly salary, not what the cutoff
  // happened to earn — a light fortnight doesn't move somebody's SSS bracket.
  const monthlyBasis = monthlyFromHourly(hourlyRate)
  const sss = sssEmployeeShare(monthlyBasis)

  const perCutoff = (monthly: number) => money(monthly / CUTOFFS_PER_MONTH)
  const scheduled = {
    sss: perCutoff(sss.total),
    philhealth: perCutoff(monthlyBasis * PHILHEALTH_EMPLOYEE_RATE),
    pagibig: perCutoff(PAGIBIG_MONTHLY),
  }
  const due = money(
    scheduled.sss +
      scheduled.philhealth +
      scheduled.pagibig +
      adjustmentDeductions
  )

  // Withheld from wages, so bounded by them. A cutoff with no pay collects
  // nothing and nets zero rather than going negative.
  const taken = money(Math.min(due, gross))
  const deductions = {
    ...scheduled,
    adjustments: adjustmentDeductions,
    due,
    total: taken,
    shortfall: money(due - taken),
  }

  return {
    hourlyRate,
    monthlyBasis,
    days: computed,
    unworkedHolidays,
    daysWorked: worked,
    regularHours: sum((day) => day.regularHours),
    overtimeHours: sum((day) => day.overtimeHours),
    approvedOvertimeHours: sum((day) => day.approvedOvertimeHours),
    nightHours: sum((day) => day.nightHours),
    nightPaidHours: sum((day) => day.nightPaidHours),
    basicPay,
    holidayPay,
    overtimePay,
    nightPay,
    adjustmentAdditions,
    gross,
    sss,
    deductions,
    net: money(gross - deductions.total),
  }
}
